spring:
  application:
    name: bookmark

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:bookmarkdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
